<a href="https://colab.research.google.com/github/falakniaz/LED-Detection-YOLOv8/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [3]:
list = [1,2,3,4,5]
list

[1, 2, 3, 4, 5]

In [5]:
multi_list = [[1,2,3,4,5], [1,2,3,4,5]]
multi_list

[[1, 2, 3, 4, 5], [1, 2, 3, 4, 5]]

In [6]:
np = np.random.rand(3,4)
np

array([[0.44401722, 0.02642792, 0.11705318, 0.10031864],
       [0.87365319, 0.05209131, 0.16416779, 0.0691222 ],
       [0.27860487, 0.97222273, 0.12877485, 0.1120313 ]])

In [7]:
np.dtype

dtype('float64')

In [8]:
tensor_2D = torch.randn(3,4)
tensor_2D

tensor([[ 0.7582,  0.2634,  0.9649,  1.1375],
        [-1.0092,  0.6911, -0.0692,  0.0150],
        [ 1.2842,  0.0413,  0.4282,  0.1666]])

In [10]:
tensor_3D = torch.zeros(2,3,4)
tensor_3D

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
tensor_3D.dtype

torch.float32

In [15]:
my_tensor = torch.tensor(np)

In [16]:
my_tensor

tensor([[0.4440, 0.0264, 0.1171, 0.1003],
        [0.8737, 0.0521, 0.1642, 0.0691],
        [0.2786, 0.9722, 0.1288, 0.1120]], dtype=torch.float64)